### ISSUE TITLE
Go directly to the game from the list of countries rather than showing a list of terms

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#102]
As proposed in https://github.com/everypolitician/gender-crowdsourcing/issues/86#issuecomment-122216611 by @tmtmtmtm 

- [x] If you pick a country with just one legislature jump directly to the latest term
- [x] If you pick a country that has more than one legislature, you get a page that asks you to choose one of those, which then in turn leads to the latest term for that legislature
- [x] Remove the page with the list of terms
- [ ] If there's more than one term, show something on the Person page that tells you which Term/level you're currently on and how many more there are, e.g. "People from the 19th Congress — complete this to unlock 7 levels" or similar
- [x] Add a `terms` (or `legislative_periods`?) table which stores (`country_code`, `legislature_slug`, `legislative_period_id`, `legislative_period_start_date`, `person_count`)
- [x] Add a `levels` table which ties together `user_id`, `term_id`, and `completed_count`
- [x] Determine which term to display using `legislative_period_start_date`
- [x] Visiting the legislature page finds the oldest term you've already played checks if you're finished, and if so starts you off on the next one or else drops you back into the middle of that one

I'm not 100% sure on the table/column names but I'm going to go with these then evolve them if they don't make sense in the code.

Should provide a fix or invalidate the following issues once done:

https://github.com/everypolitician/gender-crowdsourcing/issues/24
https://github.com/everypolitician/gender-crowdsourcing/issues/73
https://github.com/everypolitician/gender-crowdsourcing/issues/74
https://github.com/everypolitician/gender-crowdsourcing/issues/86
https://github.com/everypolitician/gender-crowdsourcing/issues/87
#115

**Comment by tmtmtmtm** [comment]
I'm assuming this should also fix, or at least get us much closer to #76 (and the related discussion in #77)?
