### ISSUE TITLE
Order of text on homepage (not logged in)

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#103]
![screen shot 2015-07-17 at 11 52 50](https://cloud.githubusercontent.com/assets/57483/8745706/66e8b6c6-2c7a-11e5-831d-54f886785d9f.png)

The buttons currently interrupt the flow of the text.

**Comment by zarino** [comment]
If we're changing the button layout, perhaps add a "Played before? Log straight in here" link to fix #169 too?

**Comment by tmtmtmtm** [comment]
When looking at the layout of the home page, the other thing that should be added is a link to the Leaderboard (or perhaps even the top N people from the leaderboard)
