### ISSUE TITLE
Add gesture for 'skip'

### ISSUE THREAD

**Issue by wrightmartin** [everypolitician/gender-balance#105]
Down probably

**Comment by zarino** [comment]
Interesting, Chris instinctively felt it should be "up".

**Comment by wrightmartin** [comment]
I thought up first, but the button is at the bottom of the diamond thingy...

**Comment by zarino** [comment]
Ah, so maybe you and Chris are on the same wavelength – he was ignoring the buttons and assuming they'd just swap to match the gestures.

**Comment by tmtmtmtm** [comment]
Is it trivial to switch the buttons even if we don't have the gesture yet? I'd rather do that before too many people start playing it…

**Comment by zarino** [comment]
@tmtmtmtm – There's a PR here that swaps the vertical order of the buttons https://github.com/everypolitician/gender-balance/pull/155
