### ISSUE TITLE
UK page slow to load

### ISSUE THREAD

**Issue by dracos** [everypolitician/gender-balance#115]
Just seems quite a bit slower than any other page I've seen so far.

**Comment by tmtmtmtm** [comment]
My presumption would be that it's because there are considerably more members in the UK than in most countries. Might be worth only loading a maximum number of cards at a time…

**Comment by dracos** [comment]
Sorry, I meant /countries/UK page which doesn't appear to load any cards?

**Comment by tmtmtmtm** [comment]
It's probably related though, as to calculate how through each term you are, it's currently looking into each of them. But this page is currently in the middle of a complete rewrite so that it doesn't have to do any of that, so hopefully that will fix this.
