### ISSUE TITLE
Buttons occasionally stop working

### ISSUE THREAD

**Issue by dracos** [everypolitician/gender-balance#116]
Sometimes, it seems when I switch gender button but not always, the button just does nothing until I move the mouse off and back on it.

**Comment by zarino** [comment]
My current hypothesis here is that the buttons being `<a>` tags is invoking some sort of browser focus behaviour. Swapping them for inert `<span>`s or similar might solve it.

**Comment by tmtmtmtm** [comment]
@zarino, unfortunately the change in #155 doesn't seem to have fixed this yet.

**Comment by zarino** [comment]
Boo.

**Comment by davea** [comment]
I'm seeing this on the live site using Safari 8.0.7 on OS X 10.10.4.

**Comment by tmtmtmtm** [comment]
Unfortunately #171 didn't resolve this one — I'm still seeing the behaviour on Safari. I've had a few instances now where repeated clicks continue to have no impact until I move my mouse slightly, upon which everything works.

(Also on Safari the card occasionally doesn't animate when I click: it just turns orange or green, pauses for a second or so, and then vanishes. No idea whether that might be connected…)

**Comment by lizconlan** [comment]
May not be related but I'm finding a similar thing happening when using the mouse to drag things around - occasionally it gets stuck with the card oddly attached to the cursor (Safari 7.1.7, Mavericks). It happened yesterday and would only recognise dropping the card I was holding into Female, which wouldn't really have suited my former MP John Randall. (Refreshed the page to reset the mouse pointer behaviour and was relieved to find the card I'd nearly misfiled waiting for me in the reshuffled pack.)

This one might "just" be an intermittent browser bug.

**Comment by zarino** [comment]
I'm investigating this now.

Discovery: when this happens, the button in question generates a `mousedown` and `mouseup` event, but no `click` event. As far as I can tell, at this point, the only way to make a `click` event register, is to move your cursor outside the element's bounds (ie: un-hover it) and then move it inside again and click.
