### ISSUE TITLE
Should only show you a person once per term

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#117]
An MP can have multiple Memberships per Legislative Period (e.g. if they change Party):
https://github.com/everypolitician/everypolitician-data/blob/master/data/Finland/Eduskunta/term-36.csv#L212-L214

We should make sure we only show one card per Person, not per Membership.

**Comment by chrismytton** [comment]
Add a method to the `LegislativePeriod` model that returns the unique people for a term and then always go through that method to get counts for total people in the term and for the list of people in the term that we display to the user.
