### ISSUE TITLE
Show better text if official data exists

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#119]
Currently, if there's no-one to categorise, because the source data supplies gender we simply show:

![screen shot 2015-07-20 at 10 53 44](https://cloud.githubusercontent.com/assets/57483/8773642/a6f48808-2ecd-11e5-8c1e-2e6ddc236fdf.png)

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon — here's another page that we overlooked, that only has placeholder text atm. 

Currently you can only get to this if the source data already includes gender for everyone, though eventually this will also happen if enough people have already given us data for that country.

**Comment by MyfanwyNixon** [comment]
> Thanks - but we're all sorted for [legislature]. 
There's plenty more to do, though - [why not pick another](http://www.gender-balance.org/countries)?

**Comment by tmtmtmtm** [comment]
Actually, your comment on #36 made me realise that if we're telling people that we don't need their input on a country, then we should be showing them the breakdown for that country.
