### ISSUE TITLE
Nowhere to go once you've finished a country

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#130]
![screen shot 2015-07-21 at 22 33 09](https://cloud.githubusercontent.com/assets/57483/8813092/88560314-2ff8-11e5-8ac8-25b2bd9f7b9b.png)

There are no links at all on this page!

**Comment by chrismytton** [comment]
- [ ] Link back to the list of countries (probably in the header bar and in the body text)
- [ ] Include the name of the country *only* if there's only one legislature
- [ ] Include the name of the country and the legislature if there is more than one legislature

**Comment by chrismytton** [comment]
Related to #76
