### ISSUE TITLE
Completeness bar when complete

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#134]
Fiji, Finland, and France all have very different completeness bars:

![screen shot 2015-07-22 at 10 24 51](https://cloud.githubusercontent.com/assets/57483/8822253/f5032e02-305b-11e5-932b-645325c184a2.png)

However, all three of these links take me to a "nothing to do" page.

**Comment by chrismytton** [comment]
The Finland case *should* be fixed by https://github.com/everypolitician/gender-balance/pull/137.
