### ISSUE TITLE
Male/female order

### ISSUE THREAD

**Issue by MyfanwyNixon** [everypolitician/gender-balance#135]
How about striking a small blow against the patriarchy by putting the 'female' button before the 'male' button? 

Just a thought...

**Comment by tmtmtmtm** [comment]
Swiftly followed by people wanting to know why we're placing the 'female' button on the 
(Unfavourable Left)[https://en.wikipedia.org/wiki/Bias_against_left-handed_people#Unfavorable_cultural_associations]?

**Comment by MyfanwyNixon** [comment]
ok ok :)
