### ISSUE TITLE
Add very basic T&Cs to the login page

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#140]
Tell people that
- we will aggregate their data and make it publicly available
- they might appear on the leader board
- …?

**Comment by davewhiteland** [comment]
maybe worth excluding leader board from spidering with a robots.txt?

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon : can you throw together a couple of very basic sentences to add to the login page that for now just explain in human-friendly text that All The Data Belong To Us, and will be used in lots of places, including research etc., and that your name may publicly appear on the site as part of the leaderboard.

**Comment by tmtmtmtm** [comment]
@davewhiteland : I'm not necessarily averse to doing so, but what's your thinking as to why it might be worthwhile? Just so that this isn't a result when googling someone?

**Comment by MyfanwyNixon** [comment]
> **The legal stuff**

>The data that you generate by using Gender Balance doesn't belong to you. It'll be placed in the public domain, and free for anyone to use. That's pretty cool, actually, because it will be available for teachers, researchers, journalists, analysts and people who want to do good things for the world.

> Your name/username won't be attached to the data, but if you're a whizz at the Gender Balance sorting game, it may appear on our leaderboard, thus giving you a pretty unique set of bragging rights.

**Comment by MyfanwyNixon** [comment]
Too long?

**Comment by tmtmtmtm** [comment]
Nope, looks good to me!

I've added it as plain paragraphs below the login buttons. @zarino: feel free to move it around or make it look different if you like :)
