### ISSUE TITLE
"You're adding to the worlds knowledge" subtitle covered up by cards

### ISSUE THREAD

**Issue by stevenday** [everypolitician/gender-balance#158]
![screen shot 2015-07-24 at 12 07 33](https://cloud.githubusercontent.com/assets/663700/8873288/edb4ae94-31fc-11e5-9b18-08911efeaa8a.png)

**Comment by stevenday** [comment]
Also, not sure I should be able to see the "you've completed this parliament" button that pokes out from below?

**Comment by tmtmtmtm** [comment]
The text is _meant_ to be covered, in that you're only supposed to see it once you're finished. If it's partially visible, then *that* is the problem :)

@zarino: would it be easy to make that final text hidden by default, and then toggle it when the user reaches the end?

**Comment by zarino** [comment]
@tmtmtmtm – yes, we could explicitly show and hide the final message. If we did that, I'd also take the opportunity to hide the buttons and google link at the bottom, since they're not applicable when you're looking at the final message.

**Comment by tmtmtmtm** [comment]
@zarino: I'm pretty sure that @chrismytton already did the work for hiding those at that point.
