### ISSUE TITLE
Doubled text at level completion

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#161]
![screen shot 2015-07-24 at 13 13 00](https://cloud.githubusercontent.com/assets/57483/8874133/c4bfe022-3205-11e5-8fb3-fd07dedac806.png)

**Comment by tmtmtmtm** [comment]
@chrismytton — my current thinking is that the period name is sufficient, without needing the legislature name as well.

It _might_ be worth adding the legislature name in brackets afterwards if there is more than one legislature for the current country, but I'm not sure that that's even worth it. Thoughts?

**Comment by chrismytton** [comment]
@tmtmtmtm Yep, I think just the period will be fine, I don't think it's even worth adding it in brackets. The user should presumably have a rough idea of which country they've just completed, after all :)
