### ISSUE TITLE
Add a 'login' button

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#169]
At the minute the only place with a Login button is the end of the onboarding game. This means every time you log out you need to go through it again, which isn't particularly friendly.

We should either offer login directly on the homepage, or, if that's too cluttered, we could potentially add it to the onboarding game itself — it's only extra click after hitting 'Play', but it's not as bad as having to go through the whole thing again.

**Comment by mhl** [comment]
I was going to report this too... +1

**Comment by chrismytton** [comment]
Related to #106
