### ISSUE TITLE
Selecting 'Albania' gives Internal Server Error

### ISSUE THREAD

**Issue by Flupsy** [everypolitician/gender-balance#181]

**Comment by chrismytton** [comment]
Error is:

```
2015-07-28T11:02:49.182769+00:00 app[web.1]: 2015-07-28 11:02:49 - NoMethodError - undefined method `already_has_gender_data?' for nil:NilClass:
2015-07-28T11:02:49.182774+00:00 app[web.1]:    /app/app.rb:139:in `block in <top (required)>'
```

**Comment by chrismytton** [comment]
Looks like we need to check if there is a country count on [this line](https://github.com/everypolitician/gender-balance/blob/4ed8c38e16d3eef665203b34779bf581885a72eb/app.rb#L139) before proceeding.

**Comment by tmtmtmtm** [comment]
This is also the case for http://www.gender-balance.org/countries/Aruba/legislatures/Estates 

These are the last two countries to have gone live on EveryPolitician

**Comment by chrismytton** [comment]
There is a deeper problem here which is that the data for Albania and Aruba is there but we haven't updated the `country_counts` table to cache the data for these countries. Once we're caching the counts correctly (see https://github.com/everypolitician/gender-balance/issues/186) we also need to fix this issue by not letting you click through to a country with no cached counts from the list of countries.
