### ISSUE TITLE
"Don't know" animation briefly reveals next-but-one card

### ISSUE THREAD

**Issue by davea** [everypolitician/gender-balance#183]
As the current card is being animated away, the next-but-one name is shown before being replaced with the correct one when the animation ends.

Safari 8.0.7 on OS X 10.10.4.

e.g. https://www.dropbox.com/s/5b5ozdfsyvs8a0k/bug.mov?dl=0

**Comment by tmtmtmtm** [comment]
@davea thanks for reporting this (and for the useful video!) 

#171 completely rewrote how this all worked, and has now been deployed. Can you check if you're still seeing this behaviour?

**Comment by davea** [comment]
Yep, that's fixed it! :+1:

**Comment by tmtmtmtm** [comment]
Yay, excellent!
