### ISSUE TITLE
Squished pictures for Australia

### ISSUE THREAD

**Issue by Flupsy** [everypolitician/gender-balance#184]

**Comment by tmtmtmtm** [comment]
Is this for all people, or all just a few? Can you attach some screenshots, as the ones I've checked look fine here:

![screen shot 2015-07-28 at 12 00 27](https://cloud.githubusercontent.com/assets/57483/8929837/50b9e1be-3520-11e5-84a4-29e194ccbecd.png)
![screen shot 2015-07-28 at 12 00 21](https://cloud.githubusercontent.com/assets/57483/8929838/50be2ada-3520-11e5-9115-7ee66bf7f54b.png)
![screen shot 2015-07-28 at 12 00 15](https://cloud.githubusercontent.com/assets/57483/8929839/50c4fa18-3520-11e5-9860-6de87cb23504.png)
![screen shot 2015-07-28 at 12 00 09](https://cloud.githubusercontent.com/assets/57483/8929840/50c68b62-3520-11e5-9964-bf6e0ffc7439.png)

**Comment by Flupsy** [comment]
It might be all images, I've only tried Australia, but this is what they look like for me.
Also the page loaded over a hundred images before it displayed anything, total load time was 41 seconds.

![1](https://cloud.githubusercontent.com/assets/1742755/8929947/3f38b234-3521-11e5-9df0-0a2d959ea60d.png)
![2](https://cloud.githubusercontent.com/assets/1742755/8929951/466f39ec-3521-11e5-8a19-917f77a0336e.png)

**Comment by chrismytton** [comment]
@Flupsy What browser is this in?

**Comment by Flupsy** [comment]
@chrismytton Firefox 39.0 on Windows 8.1.

**Comment by zarino** [comment]
Regarding the oval pictures, it looks like Firefox isn't respecting the natural aspect ratio of the images, and is instead just resizing them vertically (which is the dimension we limit in the css) and leaving the horizontal width at whatever the image started at. Should be a simple fix. @tmtmtmtm – are images always square?

**Comment by tmtmtmtm** [comment]
@zarino we know effectively nothing about the underlying images — we're just passing through raw URLs from a variety of different sources. They're all being passed through https://github.com/jpmckinney/image-proxy, though, which allows for various resizing and padding options, so I believe we could _make_ them all be square.

**Comment by chrismytton** [comment]
@zarino Yes, they will always be a square image of 140px by 140px, which is defined [in the image-proxy url here](https://github.com/everypolitician/gender-balance/blob/master/views/person_partial.erb#L7).

**Comment by zarino** [comment]
This should fix it: https://github.com/everypolitician/gender-balance/pull/189

**Comment by chrismytton** [comment]
All of the images from the Australian parliament website seem to be broken at the moment(!). But looking at other countries in Firefox seems to confirm that this has been fixed.
