### ISSUE TITLE
Add scheduled task to update cached counts

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#186]
Add a task that runs every 5 minutes to run the `rake cache` task.

**Comment by tmtmtmtm** [comment]
This information will only change when we get a fresh `countries.json` file. Can't we do these calculations as part of the process of receiving that?

**Comment by chrismytton** [comment]
In theory, yes. In practice the route that refreshes `countries.json` will timeout after 15 seconds, and the rake task will take longer than that to complete. I *think* it might just continue executing in the background but I'm not sure if that's behaviour we can rely on.

The other option is to add a background job queue to this app, which would mean we could immediately start a background job to update the cache, perhaps that's the best thing to do here to avoid the 5 minute lag time?
