### ISSUE TITLE
Don't prefetch all images

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#187]
'Time to first image' on a new country is very long, presumably because we're fetching _all_ the images.

(See also https://github.com/everypolitician/gender-balance/issues/184#issuecomment-125560501)

**Comment by zarino** [comment]
FWIW: My original prototype ajaxed cards into the game as and when they were required, so there were only ever three cards in the document. The downside is that it'd require an API endpoint to get one politician's details at a time, and that, if someone's really powering through cards, the ajax requests will be playing catchup. The upside is that images would only load once the element has been created, and the browser doesn't have to worry about potentially hundreds of hidden card elements.

**Comment by tmtmtmtm** [comment]
What order do the images load in? I guess there are really two separate issues here: how long it takes before even the first image appears, and the size implications of loading lots and lots of images prematurely. 

But at the minute it seems as if no images appear until all are loaded, which might be a symptom of them loading in reverse order, so that the front image is the last to load.

**Comment by zarino** [comment]
> which might be a symptom of them loading in reverse order

@tmtmtmtm – the cards aren't in reverse order any more.

**Comment by tmtmtmtm** [comment]
Yeah, I'm not talking about the *cards* being in reverse order here — I'm talking about the fact that the front image takes a long time to load, and musing whether that might be something to do with the order of loading of the *images*. It might be entirely unrelated, but it seems odd that I have to sit for 30 seconds or so whilst no images show, rather than the one I'm currently looking at loading early.

**Comment by zarino** [comment]
As far as I'm aware, images are loaded as you'd expect – asynchronously, and in the order they're encountered as the DOM is parsed. If the first image is taking a long time to load, it might be because the server is struggling to serve a few hundred of images at the same time, meaning *all* of the images are taking a long time to return.

**Comment by tmtmtmtm** [comment]
ITYM "as *you*'d expect" :)

But I'm definitely now worried about what will happen when I add images for the UK.

**Comment by zarino** [comment]
If we wanted the absolute minimal change, that solves the problem of hundreds of images being loaded simultaneously, but changes almost nothing else, the simplest answer would be to remove the `src` attribute from [the image element in person_partial](https://github.com/everypolitician/gender-balance/blob/5ea6c092710a1525c652539ff37bd99aebd8abf5/views/person_partial.erb#L7), like so…

```html
<img data-src="https://everypolitician-image-proxy.herokuapp.com/<%= URI.encode_www_form_component(person[:image]) %>/140/140.jpg" class="person__picture">

```

And then convert that `data-src` into an `src` using Javascript, around the time we [pull each new card into the working stack](https://github.com/everypolitician/gender-balance/blob/5ea6c092710a1525c652539ff37bd99aebd8abf5/public/js/main.js#L115). Something like this would do:

```javascript
var $newCard = $('.js-extra-cards').children().eq(0);
$newCard.attr('src', $newCard.attr('data-src'));
$newCard.appendTo($stack);
```

It's pretty hacky. And it doesn't avoid the fact that there'll be hundreds of hidden cards in the DOM. But at least it defers the image loads to one at a time, just in time.

**Comment by tmtmtmtm** [comment]
That looks plausible to me, at least as a useful first step.
