### ISSUE TITLE
I'm stuck in the never ending onboarding loop

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-balance#221]
Just tried to play Gender Balance on my phone, for the first time as far as I can remember.

I clicked the Play button on the homepage, completed the onboarding, clicked the "Play for real" button at the end of onboarding and was taken to… the onboarding again!!

I assume this is because I've got some sort of session cookie that's confusing the server. But I'm on a phone so I have no idea how to clear cookies.

If it only affects me because I'm some crazy early adopter that's fine. But I'm a bit worried that it's actually a bug *all new users* will face.

**Comment by tmtmtmtm** [comment]
Closed by #224
