### ISSUE TITLE
"Don't know" text should be split across two lines

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#225]
This is how it was:

![](https://cloud.githubusercontent.com/assets/739624/8909294/8496204a-3478-11e5-95d0-35625ce59e9e.png)

Then https://github.com/everypolitician/gender-balance/commit/90adfa6be8708f6d95778da1a6c165c6632ded70 broke the "Don't know" button so it looked flattened:

![screen shot 2015-07-30 at 11 07 48](https://cloud.githubusercontent.com/assets/22996/8982006/081977bc-36b5-11e5-91d2-da7e699a5a8a.png)

On @wrightmartin's advice I added some extra styles in https://github.com/everypolitician/gender-balance/commit/8e9a5d73195015a5ab5316b2bbbe5fd96e5021e7 so it now looks round again, but the text is all on one line:

![screen shot 2015-07-30 at 12 11 47](https://cloud.githubusercontent.com/assets/22996/8982018/2536921c-36b5-11e5-8a5d-63a570273cd3.png)

**Comment by wrightmartin** [comment]
I'll look at this today

**Comment by tmtmtmtm** [comment]
Closed by #227
