### ISSUE TITLE
Github login going round in circles

### ISSUE THREAD

**Issue by Flupsy** [everypolitician/gender-balance#240]
On iOS 8.4, when I tap 'Log in with GitHub' I just end up back at the login screen.

**Comment by tmtmtmtm** [comment]
Is there any way for you to see the browser console? There might be some useful info there (though not _that_ useful if you can't get to it…!)

Does it look like it's actually doing anything in the meantime (like going off to github), or is it an almost instant refresh of the login page?

I'm assuming you can visit github directly? Are you already logged in there? If so, have you previously authorised GenderBalance with Github? (I'm wondering if it's a series of redirects — it goes to Github to auth; Github says "Auth has already been granted, no need to ask again", and redirects back; but it's doing that in a slightly unexpected way such that we don't realise it's an acceptance?)

**Comment by Flupsy** [comment]
1. No idea how to get to browser console, or even if there is one.
2. Yeah, I can see it going to github and then back to GB.
3. I can go to github, and yes I am already logged in.

**Comment by tmtmtmtm** [comment]
Do you actually get logged in on Gender Balance, but left unexpectedly at the login screen, or does it keep asking you to log in because you're not? e.g. can you go directly to http://www.gender-balance.org/countries or does that just redirect you again to login on onboarding?

**Comment by Flupsy** [comment]
No, that url just shows me the onboarding game followed by the login page again.

**Comment by chrismytton** [comment]
@Flupsy I can't seem to reproduce this on my iPhone running iOS 8.4. Are you still seeing the redirect loop when signing in with GitHub?

**Comment by Flupsy** [comment]
Nope, I can't reproduce it either now!

**Comment by chrismytton** [comment]
OK, thanks for checking @Flupsy! Going to assume this was a transient issue and close for now, please re-open if you come across it again.
