### ISSUE TITLE
Faroe Islands incomplete, but claiming to be

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#244]
![screen shot 2015-08-08 at 12 22 20](https://cloud.githubusercontent.com/assets/57483/9150270/3bcd7d5a-3dc8-11e5-8794-9ae401a235b3.png)

![screen shot 2015-08-08 at 12 22 57](https://cloud.githubusercontent.com/assets/57483/9150271/3d3f65ae-3dc8-11e5-9260-0255e98217e5.png)

**Comment by andylolz** [comment]
The most recent legislative period has complete gender information. Earlier legislative periods don’t, though. I think that’s where this discrepancy comes from.
