### ISSUE TITLE
Haiti isn't appearing

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#257]
Haiti hasn't appeared in the list of countries yet, though https://github.com/everypolitician/everypolitician-data/pull/558 was merged over an hour ago.

**Comment by chrismytton** [comment]
I've manually intervened and it's there now. However I can't quite figure out why it didn't appear in the first place. From what I can see the webhook was delivered successfully and the update cache job ran correctly. I have a feeling https://github.com/everypolitician/app-manager/issues/24 may be somehow related, but that's more just a gut feeling than anything. Going to leave this issue open while I investigate further.

**Comment by chrismytton** [comment]
Ok, still not totally clear on exactly why Haiti didn't appear immediately, but I've fixed https://github.com/everypolitician/app-manager/issues/24 now so it *should* be much simpler to see why it failed if this happen in the future with another country.
