### ISSUE TITLE
Change users response when undo is clicked

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#261]
When the undo button (https://github.com/everypolitician/gender-balance/pull/256) is clicked it returns the previous card to the stack, however it doesn't actually update the users response, it just allows them to respond again. Ideally when the undo button is clicked it would either delete the users previous response for that card *or* it would update their response when they next vote on the card.

**Comment by lizconlan** [comment]
Responding again incorrectly adds extra points, undo should remove the point previously awarded

**Comment by andylolz** [comment]
Whoa – good point. I didn’t consider points at all.

Yeah, I think ideally points awarded and previous response would both be removed when undo is pressed.

**Comment by tmtmtmtm** [comment]
Points don't actually get _awarded_ per se — they're simply calculated dynamically based on counting responses. So either removing or replacing the previous response should be sufficient.

**Comment by andylolz** [comment]
Ohh… That suggests the previous response isn’t currently being replaced then? (which is what I’d thought happened).

**Comment by tmtmtmtm** [comment]
No, each 'vote' gets recorded separately (and thus counted separately). I don't really know the [Sequel library](http://sequel.jeremyevans.net/), but it [looks like](http://sequel.jeremyevans.net/rdoc/files/doc/release_notes/4_25_0_txt.html) we could use the `insert_conflict` method if we had PostgreSQL 9.5+. It seems we currently only have 9.4.4, though, so if there's no easy way to upgrade that we might be better doing an explicit DELETE before the INSERT.
