### ISSUE TITLE
Undo at end of level should bring the controls back

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#262]
If you complete a level:
![screen shot 2015-08-26 at 14 43 26](https://cloud.githubusercontent.com/assets/57483/9494981/f5377318-4c00-11e5-8650-9018496bd16a.png)

And *then* hit undo, you get the card back, but not the controls:

![screen shot 2015-08-26 at 14 43 36](https://cloud.githubusercontent.com/assets/57483/9494980/f51936fa-4c00-11e5-9621-35e8c87c9b0a.png)

**Comment by andylolz** [comment]
Oops! Good point.
