### ISSUE TITLE
Replace female/male with woman/man where it appears on the interface

### ISSUE THREAD

**Issue by andylolz** [everypolitician/gender-balance#272]
Suggestion from @emmajane: https://twitter.com/emmajanehw/status/641563916355653632

![screen shot 2015-09-09 at 12 37 09](https://cloud.githubusercontent.com/assets/464193/9760749/c10120f4-56ef-11e5-9d37-71b2a0939d03.png)

I wonder if this should also be changed in code? (Possibly not in the database, though.)

**Comment by tmtmtmtm** [comment]
Let's just change it on the site first, as that should be much quicker/safer than code-level changes.

Is this just on the buttons, or is there anything beyond that?

**Comment by andylolz** [comment]
> much quicker/safer than code-level changes

Kk cool.

> Is this just on the buttons, or is there anything beyond that?

It’s other places too e.g.
![screen shot 2015-09-09 at 12 57 34](https://cloud.githubusercontent.com/assets/464193/9761099/61079112-56f2-11e5-9530-f68f5a26675a.png)

**Comment by emmajane** [comment]
Doing a quick grep through the repo it looks like there are only a few places male/female are used:

- views/home_anonymous.erb:11:        <p>From Afghanistan to Zimbabwe, there are over 180 parliaments in the world — but what percentage of their members are&nbsp;female?</p>
- views/onboarding.erb:32:            <p class="person-card--advice__hint">(Press “Female”)</p>
- views/term.erb:80:        Female
- views/onboarding.erb:162:        Male
- views/term.erb:76:        Male

I haven't looked at assets (PNGs/GIFs/JPGs).

**Comment by emmajane** [comment]
Obviously changing all of the underlying code / variables / function names is an *invisible* change that you might choose to make. The long term advantage is that you might attract (or rather: not deter) a wider range of developers who are interested in the code base. HOWEVER, I think it's fine to split off that task as a "low hanging fruit" / "new contributor" task, and it does not need to be part of the updates made to the visible interface.

**Comment by andylolz** [comment]
Sounds good to me. I’ve clumsily reworded this ticket accordingly.

**Comment by laurakalbag** [comment]
Hats off for this effort. <3

**Comment by andylolz** [comment]
Sorted. Thanks all!
