### ISSUE TITLE
Show the 'balance' whilst playing 

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#277]
Have some sort of on-screen representation of the balance so-far as you play through a country — e.g. a scale tipping left or right

**Comment by zarino** [comment]
How about doing this using the existing progress bar? So, rather than what we have right now, we turn it into a little stacked bar, in the male/female colours, so it represents the proportion of genders you've assigned so far.

**Comment by tmtmtmtm** [comment]
Nice idea. My main worry is that it could be a little too subtle, but I'm sure you can come up with something wonderful to prevent that :)

**Comment by zarino** [comment]
I have a feeling subtle is good.

Quick mockup of how it might look:

![screen shot 2015-10-12 at 16 53 42](https://cloud.githubusercontent.com/assets/739624/10432253/d2494536-7101-11e5-9a85-50a1b4ec2f65.png)

**Comment by tmtmtmtm** [comment]
Yep — I'm liking that. :+1:

**Comment by andylolz** [comment]
:+1:

**Comment by zarino** [comment]
Here's a PR with the styling – https://github.com/everypolitician/gender-balance/pull/297 – hopefully @chrismytton can amend the javascript so that it animates the right bits of the bar.

**Comment by tmtmtmtm** [comment]
Closed by #297

**Comment by andylolz** [comment]
:tada: :tada: :tada:
