### ISSUE TITLE
Escape double quotes in politician names

### ISSUE THREAD

**Issue by andylolz** [everypolitician/gender-balance#281]
Refs #279.

Unescaped double quotes in names can break the `politician_id` as well as the “google them” link.

See this example from [the Falkland Islands data](https://github.com/everypolitician/everypolitician-data/blob/c729b00d/data/Falkland_Islands/Assembly/term-1989.csv#L4):

![screen shot 2015-09-17 at 08 41 32](https://cloud.githubusercontent.com/assets/464193/9927606/ff46b8c8-5d17-11e5-8f8d-c4371449d4b7.png)

Incidentally, no error is thrown when a response is given for this politician, despite the POSTed `politician_id` being incorrect.

**Comment by andylolz** [comment]
I wonder if it might also be good to strip double quotes from IDs in everypolitician-data?

**Comment by tmtmtmtm** [comment]
> I wonder if it might also be good to strip double quotes from IDs in everypolitician-data?

It's definitely worth opening a ticket to discuss at least some standards around EP ids — at the minute there are effectively none.
