### ISSUE TITLE
Names breaking at odd places

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#283]
Surely these should break between the words, rather than mid-word?

![screen shot 2015-09-20 at 15 59 29](https://cloud.githubusercontent.com/assets/57483/9981268/b2258c90-5fb0-11e5-81a5-f04bbadf5a22.png)
![screen shot 2015-09-20 at 15 59 18](https://cloud.githubusercontent.com/assets/57483/9981269/b225cfd4-5fb0-11e5-9a1e-46c4fe5e5319.png)
![screen shot 2015-09-20 at 15 59 14](https://cloud.githubusercontent.com/assets/57483/9981267/b2259d48-5fb0-11e5-8ec3-6d251bff492e.png)

**Comment by andylolz** [comment]
I think this might instead be a problem with the openpolis-scraper that pulls data into everypolitician. There are non-breaking spaces in these names [in the source](http://politici.openpolis.it/istituzione/deputati/4), and these are pulled into the everypolitician data which is causing the weird problem here.

**Comment by tmtmtmtm** [comment]
Oh, well spotted. That was pretty nasty as it was largely impossible to see in any of the data anywhere along the toolchain!

**Comment by andylolz** [comment]
Another benefit of Gender Balance – highlighting subtle data problems that may otherwise have gone unnoticed!

**Comment by tmtmtmtm** [comment]
Yep! This is why I try to play through each country as we add it — I've found quite a few issues that way.
