### ISSUE TITLE
Images not working for Ukraine

### ISSUE THREAD

**Issue by henare** [everypolitician/gender-balance#285]
Not sure if it's country-specific but Australia is working.

The image is 404ing from https://mysociety.github.io/politician-image-proxy/Ukraine/Verkhovna-Rada/19404/140x140.jpeg

![selection_001](https://cloud.githubusercontent.com/assets/48945/10153637/a5f5acb4-66a1-11e5-8351-858071ae4360.png)

**Comment by tmtmtmtm** [comment]
Hi @henare — was this for _all_ the images for Ukraine, or only a couple? I was only able to find two that were failing (both of which are now fixed), but if it was wider than that, there's probably a wider problem somewhere.

**Comment by henare** [comment]
It could very well have only been a couple. It was the first two that I checked and now I've "done" Ukraine so I can't check any more, sorry :(

**Comment by tmtmtmtm** [comment]
OK, thanks. I'll assume for now it was just those two, then, and you can let us know if you spot it again with any others.

**Comment by henare** [comment]
:+1:
