### ISSUE TITLE
Should “Skip” button actually be “Don’t know” ?

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-balance#29]
“Don’t know” has the advantage that it implies you should **know** the person’s gender if you're clicking any of the other buttons, rather than just guessing.

It has the disadvantage that it doesn't fit into a circle quite so easily.

![screen shot 2015-07-09 at 11 50 54](https://cloud.githubusercontent.com/assets/739624/8593581/e84d05aa-2630-11e5-8e89-a70fef041a0a.png)

**Comment by zarino** [comment]
The onboarding game now clearly tells people we don't want them to guess, and https://github.com/everypolitician/gender-crowdsourcing/pull/83 adds a "Don't know? Google them!" message above the buttons, which also helps get the message across.

**Comment by tmtmtmtm** [comment]
A bunch of votes for "Unsure" in IRC this afternoon, which seems like it would fit the button better, and also get the reinforcement that you _should_ be sure otherwise.

Making the button bigger would also be good.
