### ISSUE TITLE
Featured country remains at top of list after completion

### ISSUE THREAD

**Issue by lizconlan** [everypolitician/gender-balance#290]
![screen shot 2015-09-29 at 14 57 20](https://cloud.githubusercontent.com/assets/27760/10166126/8c4c2ebe-66ba-11e5-959e-ff687ec11b36.png)

**Comment by tmtmtmtm** [comment]
I think the best approach is to change the message in that case. @MyfanwyNixon , any suggestions for what we should say instead?

**Comment by MyfanwyNixon** [comment]
It depends how often /how it gets changed, I guess. is it manual?

> You've completed [this week's/the] featured country. But there are plenty more countries below.

**Comment by tmtmtmtm** [comment]
I guess there are potentially two different cases here:

1) The user has already previously completed this country, and so can't "give it a whirl"

2) The user, lured in by the promise of double points / the delight of helping us out, now plays the featured country to completion — at which point we should recognise that they've done so.

I'm not sure how easy it would be to distinguish between these (I'm guessing not trivial, but @chrismytton can jump in if there's something I not thinking of), so something that handles both is probably best. 

@MyfanwyNixon yes; it'll change manually, and though I'm guessing that it'll probably be weekly, it depends slightly on what the response to it is like.

**Comment by MyfanwyNixon** [comment]
Ah, so in case 1:
> You've already played the featured country. There are plenty more countries below, though!

And in case 2:
> Nice work - you've played the featured country. Check back soon to see if there's another chance to win double points.
