### ISSUE TITLE
Clear out duplicate responses

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#296]
Now we've got #294 merged it's not possibly for a user to have two different responses for the same person. However there is still some historic data in the database which means some people have undeserved double points from where they've used the undo button.

- [ ] Remove duplicate responses from the database, keeping only the most recent response for a user
- [ ] Add a database unique constraint to ensure no further duplicate responses can make it into the database

**Comment by andylolz** [comment]
I think duplicate responses aren’t just from undo – I _think_ they also come from rapidly pressing buttons…?

**Comment by chrismytton** [comment]
@andylolz Ah yes of course. Those responses should also hopefully be cleared up with the above steps.

**Comment by andylolz** [comment]
Great! :)

**Comment by chrismytton** [comment]
Hmm, original solution in #309 deleted more than I intended. Reopening this.

**Comment by chrismytton** [comment]
Done as part of the migration from responses to votes (#311, #314 and #315).
