### ISSUE TITLE
http://gender-balance.org/ no longer works

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#319]
gender-balance.org used to work (it's what EveryPolitician called to get data from its API), but now only www.gender-balance.org is responding

**Comment by tmtmtmtm** [comment]
@chrismytton any idea what might have changed here?

**Comment by chrismytton** [comment]
Seems to be working again now. Looking at `#activity` on IRC it seems that pluto (where the redirect is hosted) was down around the time you reported this ticket on Saturday afternoon, so I guess that was the cause of this transient issue.
