### ISSUE TITLE
Progress bar labels illegible when bar segment is very short (quite common!!)

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#320]
Originally flagged up by @zarino in https://github.com/everypolitician/gender-balance/pull/318#issuecomment-183289805.

> There's one edge case where the labels floating under the progress bars will look really weird – and that's when there's a very small number of people in that progress bar segment, eg:

![screen shot 2016-02-12 at 11 39 02](https://cloud.githubusercontent.com/assets/739624/13005907/3d344aa4-d17d-11e5-8fde-48e102dea695.png)

> It's quite hard to come up with a general purpose solution that will handle small bar segments like this, so I've left it unhandled right now. It would be good to see what the page looks like once there's real data in there, and see how common this edge case is, before we spend any serious time trying to handle it.

**Comment by tmtmtmtm** [comment]
> It would be good to see what the page looks like once there's real data in there, and see how common this edge case is

It's *very* common:

![screen shot 2016-06-19 at 08 40 16](https://cloud.githubusercontent.com/assets/57483/16175996/b1ea03a8-35f9-11e6-8861-ce3baf340f4a.png)
![screen shot 2016-06-19 at 08 40 20](https://cloud.githubusercontent.com/assets/57483/16175998/b1ea3a12-35f9-11e6-9757-32e47aa4a20c.png)
![screen shot 2016-06-19 at 08 40 25](https://cloud.githubusercontent.com/assets/57483/16175999/b1ed0bfc-35f9-11e6-9d81-34c44c07d4df.png)
![screen shot 2016-06-19 at 08 40 30](https://cloud.githubusercontent.com/assets/57483/16176000/b1f8ed50-35f9-11e6-892c-5c59aeca8006.png)
![screen shot 2016-06-19 at 08 40 37](https://cloud.githubusercontent.com/assets/57483/16176001/b1ff7dd2-35f9-11e6-94db-3ae2d776d022.png)
![screen shot 2016-06-19 at 08 40 41](https://cloud.githubusercontent.com/assets/57483/16176003/b201171e-35f9-11e6-8493-d8aa01377a71.png)
![screen shot 2016-06-19 at 08 40 45](https://cloud.githubusercontent.com/assets/57483/16176005/b2058376-35f9-11e6-9a2e-50936bab29cc.png)
![screen shot 2016-06-19 at 08 40 50](https://cloud.githubusercontent.com/assets/57483/16176002/b200dcea-35f9-11e6-97c0-e2a9b653f76d.png)
![screen shot 2016-06-19 at 08 40 56](https://cloud.githubusercontent.com/assets/57483/16176004/b202e738-35f9-11e6-8828-6d4f326742c3.png)
![screen shot 2016-06-19 at 08 41 01](https://cloud.githubusercontent.com/assets/57483/16176006/b20f4f82-35f9-11e6-9dc3-4f680e896d28.png)
![screen shot 2016-06-19 at 08 42 38](https://cloud.githubusercontent.com/assets/57483/16176011/fd2e7d44-35f9-11e6-954f-1082393888be.png)
![screen shot 2016-06-19 at 08 42 43](https://cloud.githubusercontent.com/assets/57483/16176012/fd47b16a-35f9-11e6-954f-4b003d8b7843.png)
![screen shot 2016-06-19 at 08 42 48](https://cloud.githubusercontent.com/assets/57483/16176013/fd4b4ea6-35f9-11e6-847a-ccef639a93c2.png)
![screen shot 2016-06-19 at 08 42 56](https://cloud.githubusercontent.com/assets/57483/16176016/fd50612a-35f9-11e6-914d-ada0b1119cd2.png)
![screen shot 2016-06-19 at 08 43 05](https://cloud.githubusercontent.com/assets/57483/16176014/fd4c6c50-35f9-11e6-9b27-b5f98aaa6758.png)
![screen shot 2016-06-19 at 08 43 11](https://cloud.githubusercontent.com/assets/57483/16176015/fd4e8292-35f9-11e6-8ba3-08290b098edc.png)
![screen shot 2016-06-19 at 08 43 16](https://cloud.githubusercontent.com/assets/57483/16176017/fd53b852-35f9-11e6-97d0-dc7155be9366.png)
![screen shot 2016-06-19 at 08 43 20](https://cloud.githubusercontent.com/assets/57483/16176018/fd5d3f08-35f9-11e6-98e2-63e2be405757.png)
![screen shot 2016-06-19 at 08 43 26](https://cloud.githubusercontent.com/assets/57483/16176019/fd60d0a0-35f9-11e6-90eb-f020397ec007.png)
![screen shot 2016-06-19 at 08 43 30](https://cloud.githubusercontent.com/assets/57483/16176021/fd63e768-35f9-11e6-8d81-193e017f406e.png)
![screen shot 2016-06-19 at 08 43 35](https://cloud.githubusercontent.com/assets/57483/16176020/fd63d41c-35f9-11e6-8d67-f642864c8e00.png)
![screen shot 2016-06-19 at 08 43 41](https://cloud.githubusercontent.com/assets/57483/16176022/fd63e5a6-35f9-11e6-923b-9325d5dbac62.png)
![screen shot 2016-06-19 at 08 44 14](https://cloud.githubusercontent.com/assets/57483/16176026/3659ca56-35fa-11e6-90bf-d7d9730d3173.png)
![screen shot 2016-06-19 at 08 44 19](https://cloud.githubusercontent.com/assets/57483/16176028/366055ec-35fa-11e6-975c-e9e9c9886069.png)
![screen shot 2016-06-19 at 08 44 24](https://cloud.githubusercontent.com/assets/57483/16176027/36606816-35fa-11e6-894a-fe3c72759d47.png)
![screen shot 2016-06-19 at 08 44 28](https://cloud.githubusercontent.com/assets/57483/16176029/36619f4c-35fa-11e6-9063-990eed9069a2.png)
![screen shot 2016-06-19 at 08 44 32](https://cloud.githubusercontent.com/assets/57483/16176030/3662a824-35fa-11e6-93d3-f65194378024.png)
![screen shot 2016-06-19 at 08 44 37](https://cloud.githubusercontent.com/assets/57483/16176031/366509de-35fa-11e6-80d6-2af4aa5284d7.png)
![screen shot 2016-06-19 at 08 44 41](https://cloud.githubusercontent.com/assets/57483/16176032/366dcc54-35fa-11e6-92ad-5d94060dd24c.png)
![screen shot 2016-06-19 at 08 44 47](https://cloud.githubusercontent.com/assets/57483/16176035/3677229a-35fa-11e6-9fc6-3111fee5c54a.png)
![screen shot 2016-06-19 at 08 44 50](https://cloud.githubusercontent.com/assets/57483/16176033/3675a992-35fa-11e6-877e-d702bde56059.png)
![screen shot 2016-06-19 at 08 44 55](https://cloud.githubusercontent.com/assets/57483/16176034/3676d6b4-35fa-11e6-9fdb-40ce9a752f77.png)
![screen shot 2016-06-19 at 08 45 01](https://cloud.githubusercontent.com/assets/57483/16176036/367a411e-35fa-11e6-87df-ced7e9e9bb3a.png)
![screen shot 2016-06-19 at 08 45 05](https://cloud.githubusercontent.com/assets/57483/16176037/367c06ac-35fa-11e6-9972-0b077c99e0a3.png)
![screen shot 2016-06-19 at 08 45 09](https://cloud.githubusercontent.com/assets/57483/16176038/3683e688-35fa-11e6-9e42-fc4eac562614.png)
![screen shot 2016-06-19 at 08 45 14](https://cloud.githubusercontent.com/assets/57483/16176039/3689c184-35fa-11e6-9259-c83c5549b11c.png)
![screen shot 2016-06-19 at 08 45 25](https://cloud.githubusercontent.com/assets/57483/16176040/368b07ce-35fa-11e6-9c6f-a75365b34458.png)
![screen shot 2016-06-19 at 08 45 30](https://cloud.githubusercontent.com/assets/57483/16176041/368c79f6-35fa-11e6-9a18-a4e369e05a60.png)

etc.

**Comment by zarino** [comment]
Note to self: There might be a way to solve this using flexbox, rather than absolute positioning.

**Comment by zarino** [comment]
**How we're going to fix this:** The men bar is floated left, and the women bar is floated right. Same for their labels. Labels are no longer constrained to the width of their parent.

**Comment by zarino** [comment]
PR here: https://github.com/everypolitician/gender-balance/pull/339
