### ISSUE TITLE
Confusing wording when individually complete, but generally incomplete

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#322]
![screen shot 2016-02-16 at 11 15 16](https://cloud.githubusercontent.com/assets/57483/13074847/1b945874-d49f-11e5-9ea7-a175cbc95257.png)

I find this text quite confusing. It appears in the scenario where, _I_ have played the country to completion, but not enough other people have.

I think we should change the wording here to say something here to say something along the lines of "Thanks for playing — still waiting for enough other people to play before reporting breakdown".

@MyfanwyNixon any suggestions?

**Comment by MyfanwyNixon** [comment]
Yours is fine IMO, or:

> Thanks for playing. The gender breakdown for [place] will display here, once enough other people have played.

**Comment by tmtmtmtm** [comment]
That's much better than mine! @chrismytton you happy to drop that in next time you're in the neighbourhood?

**Comment by chrismytton** [comment]
Thanks @MyfanwyNixon. @tmtmtmtm yep, will do.
