### ISSUE TITLE
Implement standard mySociety footer on gender-balance.org

### ISSUE THREAD

**Issue by MyfanwyNixon** [everypolitician/gender-balance#328]
I realise this is potentially contentious, given that GenderBalance is outside the mySociety repo - but there is currently no indication that it's affiliated to mySociety. 

This ticket https://github.com/mysociety/sysadmin/issues/676 discusses more prominent branding across all of our sites as a way of making their provenance clear.

**Comment by chrismytton** [comment]
Done in https://github.com/everypolitician/gender-balance/pull/330
