### ISSUE TITLE
i have an issue :( 

### ISSUE THREAD

**Issue by twins16** [everypolitician/gender-balance#355]
cp .env.example .env
dama@dama-root ~/Desktop/gender-balance $ nano .env
dama@dama-root ~/Desktop/gender-balance $ vagrant up
Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.

**Comment by twins16** [comment]
sudo apt-get install virtualbox-qt :+1:

**Comment by chrismytton** [comment]
@twins16 As you discovered, this error appears when VirtualBox is not installed. I'm going to close this issue now, please reopen if you're still having trouble :)
