### ISSUE TITLE
VirtualBox is complaining that the installation is incomplete. Please run `VBoxManage --version` to see the error message which should contain instructions on how to fix this error.

### ISSUE THREAD

**Issue by twins16** [everypolitician/gender-balance#356]
![screenshot from 2016-08-15 21 30 01](https://cloud.githubusercontent.com/assets/17352572/17678534/70072264-632f-11e6-9913-87da034bc199.png)

**Comment by chrismytton** [comment]
@twins16 sorry to hear you're having trouble getting this running. Can you please paste the output of `VBoxManage --version`?

**Comment by twins16** [comment]
VBoxManage --version
5.0.4_LinuxMintr102546

![screenshot from 2016-08-16 12 08 20](https://cloud.githubusercontent.com/assets/17352572/17697014/22fdedb0-63aa-11e6-8442-ef572af1d299.png)

**Comment by chrismytton** [comment]
@twins16 What the output of running `vagrant up` (without `sudo`)?

**Comment by twins16** [comment]
SLOVED THANK'S =D

2016-08-16 12:14 GMT+01:00 Chris Mytton <notifications@github.com>:

**Comment by chrismytton** [comment]
@twins16 Glad you figured it out!

**Comment by JimiPedros** [comment]
hello how did you solve this issue?

**Comment by waldyrious** [comment]
> > SLOVED THANK'S =D
>
> hello how did you solve this issue?

[Obligatory xkcd](https://xkcd.com/979/) :)

**Comment by hernandemonteiro** [comment]
try this:
apt install --reinstall linux-headers-$(uname -r) virtualbox-dkms dkms
