### ISSUE TITLE
provide a way to skip onboarding if you know it

### ISSUE THREAD

**Issue by davewhiteland** [everypolitician/gender-balance#360]
It would be convenient for powerusers if there was a way to avoid going through the onboarding if I've already done that (maybe even an undocumented feature?)

Presumbaly we'd need to store "has done onboarding OK" against the user id from login though so maybe that's not worth the trouble, but I'm logging this anyway because I just powered through the onboarding again in order to start playing.

Vaguely related to #72 in that there's a case for bypassing onboarding for a user who's clearly not only done it but done it properly :-)

**Comment by tmtmtmtm** [comment]
You shouldn't need to go through the onboarding more than once. Clicking the "log straight in" from the homepage button should take you directly to the list of countries to play. If that doesn't happen for you, can you provide a few more details on the steps you were taking?

**Comment by davewhiteland** [comment]
Yeah so maybe this was me inadvertently using different signing-in mechanisms and I was a different user. Pah.
