### ISSUE TITLE
Record that the user has completed onboarding

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/gender-balance#67]
Once they've completed the on-boarding process #66 we need to indicate that the user has completed it so we don't show it to them again.

**Comment by zarino** [comment]
Or, as @tmtmtmtm suggests, we actually save the onboarding decisions to the database (eg: "Arnold Schwartzenegger: Male") and then everything will work as expected.

It'll be possible for people to bail out of the onboarding early (after they've categorised a single card), and start real games, but that's only one of a million ways they could abuse the app.

**Comment by tmtmtmtm** [comment]
I had the opposite problem, where I got the end of the on-boarding, and hit the wrong button, and couldn't get anywhere without going through the whole thing over again…

**Comment by chrismytton** [comment]
If the user is logged in when they complete the onboarding then we set a flag on the user to `true`. If someone completes the onboarding when they're *not* logged in then we should store that they've completed it in a cookie or similar, then when they do eventually login we can check the cookie and set the flag on the user.
