### ISSUE TITLE
Improve the Onboarding examples

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-balance#71]
At the moment, the onboarding effectively requires you to assume people's gender based on their names. We should either use real people for these (perhaps https://en.wikipedia.org/wiki/List_of_actor-politicians?), or add something to the cards (or text) that tells the gender, or teaches people that guessing is a Bad Thing.

**Comment by tmtmtmtm** [comment]
Until we get real people for these, perhaps we could explicitly add something to the cards that explicitly say something like "Hint: I'm male!" or "I'm female", so we're not just teaching people to guess based on names + pictures?

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon do you have any suggestions for improving the current cards?

**Comment by MyfanwyNixon** [comment]
Perhaps with a bit of thought we can think of gendered names that represent known genders no matter where you are in the world. 

If we used the first names of internationally known people, would that help?
So for example:

Brad
Marilyn
Johnny
Albert
Leonardo
Clint
Francis

...or am I still being too westernised in my view?

Not sure how you'd negotiate the deliberately unknown ones, unless you could think of a name like Charlie where there might be well-known people of both genders?

Other than that my only suggestion is to splodge a clip-art gender-indicator such as a moustache or dangly earrings on the faces, but as they're randomly generated I'm guessing this wouldn't be easy.
