### ISSUE TITLE
Only show progress bar for current level on country page

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#74]
Prior levels should always be at 100% (other than if new data comes in, which we should work out how to solve more generally), and there's no need to show progress against levels you haven't unlocked yet.

**Comment by zarino** [comment]
Completed levels: Isn't there something satisfying about seeing your screen fill up with green bars? Like looking at the quest map in a game and seeing all the levels glittering with stars…

https://dustincb.files.wordpress.com/2013/02/photo-feb-16-10-58-58-pm.png

Upcoming levels: Isn't there something tantalising about seeing these part-filled bars, and knowing you can't quite play them yet?

**Comment by tmtmtmtm** [comment]
Showing the upcoming levels is definitely a good thing. But I'm not convinced that having to work out how far through the level they would already be once they get to start it has that much value (and it's an expensive operation that currently significantly slows down just being able to get on with playing).
