### ISSUE TITLE
Payoff on completing a term / country

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#76]
Something special should happen when you finish every term for a country

**Comment by zarino** [comment]
Some sort of variable that I can check inside of `country.erb` would be ideal. Then I can display a special screen with party poppers and champagne instead of / above the list of filled-in countries.

**Comment by tmtmtmtm** [comment]
Hopefully that will fall out of #74 — that will requiring working out what level you're currently on, so it'll be able to tell if you're all done too.

**Comment by tmtmtmtm** [comment]
(See also conversation on #77)

**Comment by tmtmtmtm** [comment]
Current version: 

![screen shot 2015-07-23 at 09 00 26](https://cloud.githubusercontent.com/assets/57483/8845731/680d11b6-3119-11e5-8d49-52ae1a4afb3d.png)

This should instead 
* Check if there are any more terms
    * If so: "You have completed (term name). There are N more levels to play. Proceed to (next term name)"
    * If not: "You have completed (country name). Choose another country"
* each can also include other messages (perhaps only on a bigger screen), possibly from @MyfanwyNixon's  big list of encouragement messages for the progress cards (#109)
* each should also be spruced up later by @zarino 
* each might also give a summary of your choices so far

**Comment by tmtmtmtm** [comment]
Reopening this, as we still want @zarino's champagne and party poppers :)
