### ISSUE TITLE
'redirect_uri_mismatch'

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#84]
Sometimes, when logging in with Github, I get a fleeting yellow warning at the top saying 'redirect_uri_mismatch':

![screen shot 2015-07-17 at 12 18 24](https://cloud.githubusercontent.com/assets/57483/8746102/0a75f6b6-2c7e-11e5-9c48-ff7dfb53cf8f.png)

Sometimes I end up logged in, sometimes not.

**Comment by chrismytton** [comment]
Fixed by https://github.com/everypolitician/gender-balance/commit/e6cf2d634cc4c9790c0f6c09b2dd0d597376b571
