### ISSUE TITLE
Block on skipping to older terms isn't working

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#86]
I can merrily go to https://gender-balance.herokuapp.com/countries/Finland/legislatures/Eduskunta/periods/31/person even without having completed the later terrms

**Comment by zarino** [comment]
And?

**Comment by tmtmtmtm** [comment]
And there's code that is meant to prevent that. If we decide that it's OK for people to 'cheat' by munging URLs, then let's just drop that code :)

**Comment by zarino** [comment]
"Oh no! Someone might hack the URL and contribute more data to our awesome project!" ;-)

If it were me, I'd just let them do it, and not bother with any code that stops them.

**Comment by tmtmtmtm** [comment]
My only concern is how it interacts with any of the performance-raising things we need to do — e.g. if we're speeding things up by only actually loading the CSV file for the level someone is currently on, and assuming that they can only have gotten there by completing the previous terms, someone simply trying this sort of 'hack' out to see if it would work could potentially break their ability to ever get back again, depending on how things get implemented.

**Comment by tmtmtmtm** [comment]
I'm also a little concerned that this could be a symptom of a larger bug in how we calculate completeness, that might have less desirable side-effects elsewhere.

**Comment by chrismytton** [comment]
> And there's code that is meant to prevent that.

I don't think there is actually! The code for "calculating" a recent term is currently [very rudimentary/hacky and happens entirely in the template](https://github.com/everypolitician/gender-crowdsourcing/blob/a1fb2b60e2ccf82a92135f8413e8a028b390688f/views/country.erb#L12-L31)!

Once we've got better tracking of which "levels" the user has and hasn't completed (#74) then this should naturally fall out of that, as should a fix for #87.

**Comment by tmtmtmtm** [comment]
That's the code I was talking about. I read that as saying that the "Complete your first term to unlock terms further in the past" part should display if you try to jump ahead. 

But it seems it's in an `if !@previous_term_complete` block that in turn is wrapped in an `if @previous_term_complete`, so presumably can't ever be reached…

But, yes, this in itself isn't something that needs attention.

**Comment by chrismytton** [comment]
Ah, `@previous_term_complete` gets [reset just before the check to display that block of text](https://github.com/everypolitician/gender-crowdsourcing/blob/a1fb2b60e2ccf82a92135f8413e8a028b390688f/views/country.erb#L18)  :scream:. As I said, it's all a bit terrible and needs improving.

**Comment by tmtmtmtm** [comment]
Urk. Well, either way, it's not working :)

I'm wondering actually if this is a symptom that the approach of even having the term in the URL might be wrong. Perhaps you should just choose the legislature (and in most countries that will short-circuit to just picking the country, as there'll only be one), and then it works out which level you're on and just starts showing you people?

We can (and definitely _should_) still have end of level cheers and whoops and all that stuff, but going to the next level would then just be a reload of the same page.

(This might also make the other case easier where a single new member is elected in the current term, which you've already otherwise completed…)
