### ISSUE TITLE
Can only play a single chamber?

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#87]
I can only get to the Australian House of Representatives, not the Senate

![screen shot 2015-07-16 at 15 45 02](https://cloud.githubusercontent.com/assets/57483/8726375/c40d5e50-2bd1-11e5-8011-077482340803.png)

It's unclear whether this works the same way as unlocking old levels, and whether I'd then need to categorise everyone (potentially back over hundreds of years) in a Lower house before progressing to the Upper, etc.

**Comment by chrismytton** [comment]
The simple fix for this is to reset `@previous_term_complete` and `@first_term` at the [beginning of this loop](https://github.com/everypolitician/gender-crowdsourcing/blob/a1fb2b60e2ccf82a92135f8413e8a028b390688f/views/country.erb#L7). However that would just be piling hacks on top of hacks so instead I'm going to leave this until #74 is done, which should naturally provide a fix for this bug.
