### ISSUE TITLE
Explain why login is required

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/gender-balance#92]
We need some text to tell people why we're making them log in just to play.

**Comment by tmtmtmtm** [comment]
@MyfanwyNixon suggested: 

Log in to play

Logging in takes 3 seconds -- and then Gender Balance will remember your achievements for the next time you play, unlocking new levels as you progress.

---

That's definitely a good start, although I think we should also have at least _something_ that explains why _we_ also need it: it's not solely for _their_ benefit.

**Comment by MyfanwyNixon** [comment]
I reckoned people mainly care about themselves ;)

But you could add a line:

> It also ensures you're a real person, and not a nasty spambot.

or:

> It also helps ensure good quality submissions.

(although personally,  I think that's a hard concept to try and explain before they've understood the game, and also might put people off more than no explanation at all would).

**Comment by tmtmtmtm** [comment]
They do, but judging by the feedback so far, expressing it solely in those terms might well trigger a response of "Oh, but I don't really care about that, so why can't you let me just play without that". Explaining that actually it's required so that we can be more sure that the answers are good enough to actually share with researchers etc is more likely to be persuasive to those sorts of people, I think.

**Comment by MyfanwyNixon** [comment]
ok:

> It also helps us to ensure good quality submissions, which will be important because the data processed by Gender Balance will be available for researchers, journalists and other analysts to use.

**Comment by tmtmtmtm** [comment]
:+1:
