### ISSUE TITLE
New button layout

### ISSUE THREAD

**Issue by zarino** [everypolitician/gender-balance#95]
The "I don't know" button (currently "Skip") should be at least as big as the two gender choices, otherwise we're making it too hard for people to be honest and *not guess if they don't know*.

**Comment by tmtmtmtm** [comment]
Related, #94 and #29

**Comment by zarino** [comment]
I'm thinking something like:

![buttons](https://cloud.githubusercontent.com/assets/739624/8772649/cabb7ff6-2ec5-11e5-947a-00e51412fdc1.jpg)

(That's a preview of how it'd look on the smallest screen we support: 320×480, minus toolbars.)

I can't work out a way to keep the circles while also making the "Don't know" circle as big as the other two *and* making it fit on small screens.

We could revert back to the circles once we're on a wider screen.
